# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jam', '0002_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(blank=True, max_length=255, null=True)),
                ('doubanid', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('author_intro', models.TextField()),
                ('publisher', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
                ('ratenumber', models.IntegerField()),
                ('tags', models.CharField(max_length=255)),
                ('thumbnail', models.CharField(max_length=255)),
                ('imgs', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('catalog', models.TextField()),
                ('pages', models.IntegerField()),
                ('downloadnum', models.IntegerField(blank=True, default=0, null=True)),
                ('filelocation', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('filename', models.CharField(max_length=255)),
            ],
        ),
    ]
